"""add_created_by_to_organizations

Revision ID: 8fef31cf57d5
Revises: deb779a4bb05
Create Date: 2026-03-30 10:16:49.664696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fef31cf57d5'
down_revision = 'deb779a4bb05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('created_by', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'created_by')
    # ### end Alembic commands ###
