"""initial_auth_tables

Revision ID: deb779a4bb05
Revises: e005ae2d4327
Create Date: 2026-03-24 16:02:16.275657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb779a4bb05'
down_revision = 'e005ae2d4327'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
